database:
  host: "91.227.114.69"
  port: 3306
  name: "s442_login_database"
  user: "u442_Mk05XSadkW"
  password: "o6@x1Ti2urufj!j2Y.QCJRX."

spawn:
  verified:
    world: world
    x: 100.5
    y: 65
    z: -100.5
    yaw: 90
    pitch: 0

  unverified:
    world: world
    x: 0.5
    y: 65
    z: 0.5
    yaw: 180
    pitch: 0

title:
  fade_in: 10
  stay: 70
  fade_out: 20
